export const MateriasCarrera = {
  "1": [
    "Tópicos Avanzados de Programación",
    "Ecuaciones Diferenciales",
    "Lenguajes y Autómatas I", 
    "Taller de Sistemas Operativos",
    "Principios Elec. y Aplic. Dig.",
    "Fundamento De Base de Datos",
    "Métodos Numéricos",
    "Fund. de Telecomunicaciones",
    "Lenguajes y Autómatas II",
    "Taller de Bases de Datos",
    "Fund. de Ing. de Software",
    "Arquitectura de Computadoras",
    "Simulación",
    "Redes de Computadoras",
    "Graficación",
    "Admin. de Bases de Datos",
    "Ing. de Software",
    "Lenguajes de Interfaz",
    "Prog. y Lógica Funcional",
    "Conmutación y Enrutamiento de Redes de Datos",
    "Taller de Investigación I",
    "Prog. Web",
    "Gestión de Proyectos de Software",
    "Sistemas Programables",
    "Prog. Móvil I",
    "Inteligencia Artificial",
    "Admin. de Redes",
    "Taller de Investigación II",
    "Prog. Web II",
    "Prog. Web III",
    "Investigación de Operaciones",
    "Prog. Móvil II",
    "Form. y eval. de proy. de inv."
  ],
  "2": [
    "Cálculo Diferencial",
    "Taller de Ética",
    "Fund. de Investigación",
    "Prog. Básica",
    "Fund. de Dibujo",
    "Química Aplicada",
    "Cálculo Integral",
    "Álgebra Lineal",
    "Prog. Aplicada",
    "Tecnología de Materiales",
    "Metrología",
    "Cálculo Vectorial",
    "Estática",
    "Métodos Numéricos",
    "Electricidad y Magnetismo",
    "Termodinámica",
    "Procesos de Manufactura",
    "Ecuaciones Diferenciales",
    "Mecánica de Materiales",
    "Dinámica",
    "Circuitos Eléctricos",
    "Mecánica de Fluidos",
    "Habilidades Directivas",
    "Máquinas Eléctricas",
    "Diseño de Elementos",
    "Análisis de Mecanismos",
    "Electrónica Analógica",
    "Transferencia de Calor",
    "Control Estadístico",
    "Desarrollo Sustentable",
    "Tribología",
    "Instrumentación Electrónica",
    "Motores de Combustión",
    "Admin. de Sistemas",
    "Circuitos Neumáticos",
    "Electrónica de Potencia",
    "Control de Calidad",
    "Ing. de Costos",
    "Diseño Asistido",
    "Elementos Automotrices",
    "Seminario de Titulación",
    "Automatización Industrial"
  ],
  "3": [
    "PENDIENTE"
  ],
  "4": [
    "Precálculo",
    "Comp. Lectora",
    "Mecánica Clásica",
    "Lógica Mat.",
    "Fund. de Inv.",
    "Com. Humana",
    "Taller de Ética",
    "Des. Sustentable",
    "Cálculo Dif.",
    "Tópicos Física",
    "Med. Eléctricas",
    "Química",
    "Álgebra Lin.",
    "Cálculo Vec.",
    "Economía",
    "Proc. Fabricación",
    "Est. Inferencial I",
    "Metrología",
    "Admin. Proyectos",
    "Inv. Operaciones I",
    "Anál. Numérico",
    "Circuitos Eléc. I",
    "Teoría Electromag.",
    "Microcontroladores",
    "Contr. Lóg. Prog.",
    "Des. Profesional",
    "Amps. Op.",
    "Diseño con Trans.",
    "Control II",
    "Transm. Datos Ind.",
    "Automat. Emp.",
    "Admin. Gerencial",
    "Taller Inv. I",
    "Instrum. Opto.",
    "Contr. Digital",
    "Tecnolog. Automat.",
    "Automat. Supervis. Cal.",
    "Des. y Eval. Proy.",
    "Taller Inv. II",
    "Intro Telecom.",
    "Electr. Potencia",
    "Señ. Analóg. en Dis. Prog.",
    "Integración Sist. Autom."
  ],
  "5": [
    "Cálculo Diferencial",
    "Taller de Ética",
    "Fund. de Investigación",
    "Prog. Básica",
    "Fund. de Dibujo",
    "Química Aplicada",
    "Cálculo Integral",
    "Álgebra Lineal",
    "Prog. Aplicada",
    "Tecnología de Materiales",
    "Metrología",
    "Cálculo Vectorial",
    "Estática",
    "Métodos Numéricos",
    "Electricidad y Magnetismo",
    "Termodinámica",
    "Procesos de Manufactura",
    "Ecuaciones Diferenciales",
    "Mecánica de Materiales",
    "Dinámica",
    "Circuitos Eléctricos",
    "Mecánica de Fluidos",
    "Habilidades Directivas",
    "Máquinas Eléctricas",
    "Diseño de Elementos",
    "Análisis de Mecanismos",
    "Electrónica Analógica",
    "Transferencia de Calor",
    "Control Estadístico",
    "Desarrollo Sustentable",
    "Tribología",
    "Instrumentación Electrónica",
    "Motores de Combustión",
    "Admin. de Sistemas",
    "Circuitos Neumáticos",
    "Electrónica de Potencia",
    "Control de Calidad",
    "Ing. de Costos",
    "Diseño Asistido",
    "Elementos Automotrices",
    "Seminario de Titulación",
    "Automatización Industrial"
  ],
  "6": [
    "Quím. Inorgánica",
    "Precálculo",
    "Dibujo Asist. Comp.",
    "Taller de Ética ",
    "Fund. de Investigación",
    "Biología ",
    "Est. Inferencial I",
    "Metrología",
    "Admin. Proyectos",
    "Inv. Operaciones I",
    "Análisis Numérico",
    "Circuitos Eléc. I",
    "Teoría Electromag.",
    "Microcontroladores",
    "Contr. Lóg. Prog.",
    "Automat. Emp.",
    "Admin. Gerencial",
    "Taller Inv. I",
    "Instrum. Opto.",
    "Contr. Digital",
    "Tecnolog. Automat.",
    "Automat. Supervis. Cal.",
    "Des. y Eval. Proy.",
    "Taller Inv. II",
    "Intro Telecom.",
    "Electr. Potencia",
    "Señ. Analóg. en Dis. Prog.",
    "Integración Sist. Autom."
  ],
  "7": [
    "PENDIENTE"
  ],
};
